name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Select option for build or deployement'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terraform
      run: |
        echo  "Log level: ${{ github.event.inputs.logLevel }}"
        sudo apt-get update
        sudo apt-get install -y unzip
        wget https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip
        unzip terraform_0.14.3_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version

